### ISSUE TITLE
Config files for navier-stokes

### ISSUE THREAD

**Issue by wanghonghui1998** [LouisSerrano/coral#2]
Hi there,

Firstly, I'd like to express my appreciation for sharing your code. The results you've achieved are truly impressive!

However, I noticed that only the configuration files for the shallow-water dataset have been provided in the Dynamics Modeling section. Could you please also share the configuration files for the Navier-Stokes dataset? This would greatly assist me in reproducing the results.

Additionally, I encountered some incomplete commands in the Dynamics Modeling section. For instance:
>>python3 inr/inr.py "data.sub_from=$sub_from" "data.same_grid=$same_grid"

Could you kindly clarify the values of $sub_from and $same_grid? It would be immensely helpful if you could provide the complete scripts.

Thank you for your assistance.

**Comment by LouisSerrano** [comment]
Hi, sorry I did not have time to clean the repo yet. You can find some scripts for training on navier-stokes `coral/bash_dynamics/navier-stokes`, the two main scripts to look at are `inr.sh` and `ode.sh`, the rest are for baselines or were used for preliminary research. Please tell me if this helps you. 

For sub_from, I think it depends on the dataset. For Navier-Stokes, for the basic experiments you can use sub_from=1 and sub_tr=4 and sub_te=4. This lets you subsample the original 256x256 grid to 64x64. If you want to use irregular subsampling, then I guess the same_grid parameter should be set to True for the main paper experiments and to False for the experiments in the appendix (those with different grids for each initial condition). Then the tricky part, is to compute the correct sub_sampling ratio by hand. For instance if you want to take 25% of the grid (of the 64x64 grid), you can keep sub_from=1  but you need to pass sub_tr=0.25*(1/4)**2 = 0.015625. 

Let me know if this is clear.
Best

**Comment by wanghonghui1998** [comment]
Many thanks for your detailed reply! It addresses my concerns.

**Comment by wanghonghui1998** [comment]
Hi there,

I have noticed a potential issue regarding the resolution of the training and test data. It seems that the test data is subsampled once using the 'sub_from' argument, whereas the training data is subsampled twice with the same 'sub_from' argument in  
https://github.com/LouisSerrano/coral/blob/ec8ca96df75727dd7b8191fe05c8ad4714f882a8/coral/utils/data/load_data.py#L393-L395
and https://github.com/LouisSerrano/coral/blob/ec8ca96df75727dd7b8191fe05c8ad4714f882a8/coral/utils/data/load_data.py#L405-L407

For instance, in the config file 'bash_dynamics/navier-stokes/ode.sh', the parameters are set as 'sub_from=2', 'sub_tr=0.2', and 'sub_te=0.2'. As a result, the training data would have a resolution of '64x64x0.2', while the test data would have a resolution of '128x128x0.2'.

Could you kindly check if this issue affects the actual configurations to reproduce the results reported in your paper? Additionally, could you provide the values of sub_from, sub_tr, and sub_ts for both the regular grid and irregular grid settings?

Thank you!

**Comment by LouisSerrano** [comment]
Hi, sorry for the late response. You are right, I think there is an issue in the default config file. In the paper's experiments, we set `sub_from=1` to avoid this issue. 
Therefore, the different configurations for NS are the following: 
* $\pi=100$%: `sub_tr=4`, and `sub_te=4`;
* $\pi=20$%: `sub_tr=0.0125`, and `sub_te=0.0125` (0.25x0.25x0.20); 
*  $\pi=5$%: `sub_tr=0.003125`, and `sub_te=0.003125` (0.25x0.25x0.05).
And, the different configurations for SW are the following: 
* $\pi=100$%: `sub_tr=2`, and `sub_te=2`;
* $\pi=20$%: `sub_tr=0.05`, and `sub_te=0.05` (0.50x0.50x0.20); 
*  $\pi=5$%: `sub_tr=0.0125`, and `sub_te=0.0125` (0.50x0.50x0.05).

**Comment by wanghonghui1998** [comment]
Thank you so much! Following your suggestion, I have successfully reproduced the experimental results.
